name = "OPFLearn"
uuid = "426fd8f4-da10-4833-b320-d1e833f8a26f"
authors = ["Trager Joswig-Jones"]
repo = "https://github.com/NREL/OPFLearn.jl"
version = "0.1.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
InfrastructureModels = "~0.6"
Ipopt = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9"
JSON = "~0.18, ~0.19, ~0.20, ~0.21"
JuMP = "~0.21.6"
OnlineStats = "1"
OnlineStatsBase = "1"
MathOptInterface = "~0.9, 0.10"
PowerModels = "0.18"
SCS = ">= 0.6.3"
StatsBase = "0.33"
julia = "^1"

[extras]
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
